DataStructure: Template Definition
Template Definition
Class template must be defined in .hpp to avoid link error.
Functions
template<class Type >
ostream & bonzo::operator<< (ostream &, const primitive_node< Type > &)
Bound friend function template.
template<class Type >
istream & bonzo::operator >> (istream &, primitive_node< Type > &)
Bound friend function template.
bonzo::primitive_node< Type >::primitive_node ()
Default constructor.
bonzo::primitive_node< Type >::primitive_node (const Type &)
Normal constructor.
bonzo::primitive_node< Type >::primitive_node (const primitive_node &)
Copy constructor.
void bonzo::primitive_node< Type >::set_node (Type)
Set node value.
Type bonzo::primitive_node< Type >::get_node () const
Get node value.
bool bonzo::primitive_node< Type >::is_prev_null ()
Check if prev is a nullptr.
bool bonzo::primitive_node< Type >::is_next_null ()
Check if next is a nullptr.
bool bonzo::primitive_node< Type >::is_left_null ()
Alias to is_prev_null.
bool bonzo::primitive_node< Type >::is_right_null ()
Alias to is_next_null.
primitive_node & bonzo::primitive_node< Type >::operator= (const primitive_node &)
Operator =.
Detailed Description
Class template must be defined in .hpp to avoid link error.
Function Documentation
template<class Type > Type bonzo::primitive_node< Type >::get_node () const
Get node value.
Returns
node value. Return by copy.
References bonzo::primitive_node< Type >::node.
{
     return node;
 }
template<class Type > bool bonzo::primitive_node< Type >::is_left_null () inline
Alias to is_prev_null.
Return values
true prev is a nullptr.
false prev is not a nullptr.
References bonzo::primitive_node< Type >::is_prev_null().
{
     return is_prev_null();
 }
template<class Type > bool bonzo::primitive_node< Type >::is_next_null () inline
Check if next is a nullptr.
Alias to is_next_null.
Check if next is nullptr.
Return values
true next is a nullptr.
false next is not a nullptr.
References bonzo::primitive_node< Type >::next.
Referenced by bonzo::primitive_node< Type >::is_right_null().
{
     return next == nullptr;
 }
template<class Type > bool bonzo::primitive_node< Type >::is_prev_null () inline
Check if prev is a nullptr.
Check if prev is nullptr.
Return values
true prev is a nullptr.
false prev is not a nullptr.
References bonzo::primitive_node< Type >::prev.
Referenced by bonzo::primitive_node< Type >::is_left_null().
{
     return prev == nullptr;
 }
template<class Type > bool bonzo::primitive_node< Type >::is_right_null () inline
Alias to is_next_null.
References bonzo::primitive_node< Type >::is_next_null().
{
     return is_next_null();
 }
template<class Type > istream & bonzo::operator >> (istream & is, primitive_node< Type > & lhs)
Bound friend function template.
Overload operator >>.
Parameters
is An istream instance to input stream, usually cin.
lhs A reference to primitive_node, which will be written by input.
Returns
is An istream instance.
References bonzo::primitive_node< Type >::node.
{
     is >> lhs.node;
     return is;
 }
template<class Type > ostream & bonzo::operator<< (ostream & os, const primitive_node< Type > & rhs)
Bound friend function template.
Overload operator <<.
Parameters
os An ostream instance to stream output, usually cout.
rhs A reference to primitive_node, which will be print out.
Returns
os An ostream instance.
{
     os << rhs.node << endl;
     return os;
 }
template<typename Type > primitive_node< Type > & bonzo::primitive_node< Type >::operator= (const primitive_node< Type > & rhs)
Operator =.
Overload operator =.
Parameters
rhs A reference to primitive_node, will be assigned to *this.
Returns
*this for cascading assignment.
References bonzo::primitive_node< Type >::next, bonzo::primitive_node< Type >::node, and bonzo::primitive_node< Type >::prev.
{
     node = rhs.node;
     prev = rhs.prev;
     next = rhs.next;
     return *this;
 };
template<class Type > bonzo::primitive_node< Type >::primitive_node ()
Default constructor.
See also
primitive_node(const Type&)
primitive_node(const primitive_node&)
References bonzo::_DEBUG_ON, and bonzo::print_dbg_msg().
                                      : prev(nullptr), next(nullptr), left(prev), right(next)/*, is_left_null(&primitive_node::is_prev_null), is_right_null(&primitive_node::is_next_null)*/{
     print_dbg_msg(_DEBUG_ON, "primitive_node() is called");
     return;
 };
template<class Type > bonzo::primitive_node< Type >::primitive_node (const Type & rhs)
Normal constructor.
Parameters
rhs Initialize node from rhs.
See also
primitive_node()
primitive_node(const primitive_node&)
References bonzo::_DEBUG_ON, bonzo::primitive_node< Type >::node, and bonzo::print_dbg_msg().
template<class Type > bonzo::primitive_node< Type >::primitive_node (const primitive_node< Type > & rhs)
Copy constructor.
Parameters
rhs A reference to another primitive_node. Memberwisely initialize from rhs.
See also
primitive_node()
primitive_node(const Type&)
References bonzo::_DEBUG_ON, bonzo::primitive_node< Type >::next, bonzo::primitive_node< Type >::node, bonzo::primitive_node< Type >::prev, and bonzo::print_dbg_msg().
template<class Type > void bonzo::primitive_node< Type >::set_node (Type rhs)
Set node value.
Set node value by rhs.
Parameters
rhs The value being assigned to node. Call by value.
References bonzo::primitive_node< Type >::node.
{
     node = rhs;
     return;
 }